export const LOAD_CATEGORY = 'LOAD_CATEGORY';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRO_CATE = 'LOAD_PRO_CATE';
export const LOAD_DETAIL = 'LOAD_DETAIL';
export const ADD_CART = 'ADD_CART';
export const UPDATE_QTY_CART = 'UPDATE_QTY_CART';
export const DELETE_PRODUCTS_CART = 'DELETE_PRODUCTS_CART';



